### ISSUE TITLE
Expected conv2d_input to have shape 44

### ISSUE THREAD

**Issue by LukasSliacky** [musikalkemist/Deep-Learning-Audio-Application-From-Design-to-Deployment#1]
Hi Valerio, 

really thank you for your great series - they is really useful.

I tried run your code but on episode 4 (Making Predictions with the Speech Recognition System) but i have problem with error: 

```
ValueError: Error when checking input: expected conv2d_input to have shape (44, 13, 1) but got array with shape (39, 13, 1)
``` 

When i try print data (MFCCs) on line 38, i see really only 39 block of numbers.

(I mean one block of numbers:
```
[-3.97769470e+02  1.14391960e+02 -3.56520081e+01 -1.58262463e+01
  -3.96851883e+01  1.63613205e+01  2.23767796e+01  1.18182526e+01
   2.13198013e+01 -1.87037945e-01 -1.15992937e+01 -4.41460037e+00
  -6.91393471e+00]
```
)
Please, can you help me with this issue? 

Can you explain me, why is there only 39 block of numbers or how can change to to expected 44?

Thank you.

Lukas

**Comment by LukasSliacky** [comment]
Sorry, probably it was problem on my side.
When i try clone your code, it works. I have to analyze my source.

**Comment by musikalkemist** [comment]
Sounds great! Next time, can you please ask questions directly commenting
on YouTube? This way the whole community can benefit from the conversation
:)

Thanks!
V
